### ISSUE TITLE
Need packages for this in Fedora.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman-tui#7]

**Comment by navidys** [comment]
Hi @rhatdan 

- rpm spec file + release script to bump version created ( [#8 ](https://github.com/containers/podman-tui/pull/8) ) and working under with fedora corp
- A ticket under [packager-sponsors](https://pagure.io/packager-sponsors/issue/519) has been created in order to be a member of  packager group to have it in Fedora.

**Comment by rhatdan** [comment]
Great @navidys
