### ISSUE TITLE
CI needs

### ISSUE THREAD

**Issue by baude** [containers/podman-tui#9]
Do you have any tests you would like to run in CI? How about a DCO check?

**Comment by navidys** [comment]
Hi @baude 
At this stage the only test available is just go fmt, lint and vet which is part if Makefile (make validate). In near future I will add some tests (unit, functionality, ...).
 
Apart from github workflow DCO check (#10 ) and default app there is no specific test for DCO check, do you think that's sufficient enought?

**Comment by navidys** [comment]
Hi @baude 
Added 40 functionality tests #12

**Comment by baude** [comment]
I seem to be unable to run the tests successfully on my laptop. I see a lot of `   error connecting to /tmp/tmux-0/default (No such file or directory)`.  can you advise?

**Comment by navidys** [comment]
Hi @baude 
Are you running the tests with root account ? 
I have fixed the issue with running the tests under root account: #14 
Is it OK to try and let me know if you still facing issue on your laptop.

**Comment by baude** [comment]
It fails with both.  Are there dependencies I need or services or anything ?

**Comment by navidys** [comment]
Apart from tmux package, in setup function it will try to start podman.socket via systemctl. 
if ./bin/podman-tui doesn't exist (make binary) the tests will fail as well. 
I've tested on vagrant box FC34 and FC35 and it was OK (there were some issue that I've fixed them in #14 )
Is it possible to attach full error logs ?

**Comment by navidys** [comment]
Hi @baude 
I faced similar issue you faced. 

- The issue was podman-tui was not build (make binary) before running the test, also if we are not under root directory of the project then we need to set and export the "PODMAN_TUI" variable (pointing to bin/podman-tui). 

- I have updated some of the tests and the helper (#25  already merged) to display the correct error messages, [tests readme ](https://github.com/containers/podman-tui/blob/main/test/README.md ) also updated to includes above information as well.
